name: Update cmark-gfm

on: workflow_dispatch

jobs:
  update:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update
        run: sh ./update_cmark_gfm.sh
      - name: Check build
        run: swift build
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update to latest cmark-gfm
